language: python

python:
  - 3.5

cache:
  - pip

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test -v --color=yes --cov=.

after_success:
  - codecov
